project:
  type: website
  output-dir: docs

website:
  title: "Welcome to StratoBayes"
  description: "Automated stratigraphic correlation and age modelling"
  page-navigation: false
  site-url: "https://stratobayes.github.io"

  sidebar:
    style: "docked"
    search: true
    logo: "images/logo-2.png"
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Software"
        href: software.qmd
        contents:
          - text: "Installation"
            href: software.html#installation
          - text: "Vignette"
            href: vignettes/StratoBayes.qmd
          - text: "Tutorial - Permian case study"
            href: tutorial-1/StratoBayes-Tutorial-1.qmd
      - text: "Preprint"
        href: https://egusphere.copernicus.org/preprints/2025/egusphere-2025-1355/
      - text: "Website"
        href: https://stratobayes.com
      - text: "Workshop"
        href: https://stratobayes.github.io/workshop

format:
  html:
    theme: cosmo
    toc: false

editor: visual

resources:
  - bin/*
  - bin/**
  - tutorial-1/StratoBayes-Tutorial-1.zip**

